# Базовый образ с Node.js
FROM node:22-alpine

# Устанавливаем git
RUN apk add --no-cache git

# Рабочая директория
WORKDIR /app

# Клонируем репозиторий
ARG GIT_BRANCH=feature/frontend
ARG GIT_REPO
RUN git clone -b ${GIT_BRANCH} ${GIT_REPO} . && \
    rm -rf .git

# Устанавливаем зависимости через yarn
RUN yarn install

# Копируем всё (если нужно добавить локальные файлы)
COPY . .

# Открываем порт
EXPOSE 3000

# Команда для разработки с hot-reload
CMD ["yarn", "dev"]