services:

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .  # меняем на текущую директорию
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    container_name: cybertech-frontend

  backend:
    build:
      context: .  # меняем на текущую директорию
      dockerfile: backend.dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    container_name: cybertech-backend