import { Metadata } from 'next';
import './reset.css';

export const metadata: Metadata = {
	title: 'Cyber Tech',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ru'>
			<body>{children}</body>
		</html>
	);
}
